package com.client.legitskillissue.module;

import com.client.legitskillissue.module.impl.combat.AimAssistMod;
import com.client.legitskillissue.module.impl.combat.AntiBotMod;
import com.client.legitskillissue.module.impl.combat.AutoClickerMod;
import com.client.legitskillissue.module.impl.combat.AutoPotMod;
import com.client.legitskillissue.module.impl.combat.AutoSoupMod;
import com.client.legitskillissue.module.impl.combat.BacktrackMod;
import com.client.legitskillissue.module.impl.combat.BlockHitMod;
import com.client.legitskillissue.module.impl.combat.CriticalsMod;
import com.client.legitskillissue.module.impl.combat.FastBowMod;
import com.client.legitskillissue.module.impl.combat.HitBoxMod;
import com.client.legitskillissue.module.impl.combat.HitDelayFixMod;
import com.client.legitskillissue.module.impl.combat.ReachMod;
import com.client.legitskillissue.module.impl.combat.SilentAuraMod;
import com.client.legitskillissue.module.impl.combat.TargetSelectorMod;
import com.client.legitskillissue.module.impl.combat.TriggerBotMod;
import com.client.legitskillissue.module.impl.combat.VelocityMod;
import com.client.legitskillissue.module.impl.combat.WTapMod;
import com.client.legitskillissue.module.impl.exploit.AntiAimXMod;
import com.client.legitskillissue.module.impl.exploit.AntiBlindXMod;
import com.client.legitskillissue.module.impl.exploit.AntiCactusXMod;
import com.client.legitskillissue.module.impl.exploit.AntiFireXMod;
import com.client.legitskillissue.module.impl.exploit.AntiKnockbackXMod;
import com.client.legitskillissue.module.impl.exploit.AntiPotionXMod;
import com.client.legitskillissue.module.impl.exploit.AntiSpamXMod;
import com.client.legitskillissue.module.impl.exploit.AntiWaterXMod;
import com.client.legitskillissue.module.impl.exploit.AutoAcceptXMod;
import com.client.legitskillissue.module.impl.exploit.AutoArmor2XMod;
import com.client.legitskillissue.module.impl.exploit.AutoBuildXMod;
import com.client.legitskillissue.module.impl.exploit.AutoClickerXMod;
import com.client.legitskillissue.module.impl.exploit.AutoDropXMod;
import com.client.legitskillissue.module.impl.exploit.AutoEatXMod;
import com.client.legitskillissue.module.impl.exploit.AutoFarmXMod;
import com.client.legitskillissue.module.impl.exploit.AutoFishXMod;
import com.client.legitskillissue.module.impl.exploit.AutoHealXMod;
import com.client.legitskillissue.module.impl.exploit.AutoJumpXMod;
import com.client.legitskillissue.module.impl.exploit.AutoLeaveXMod;
import com.client.legitskillissue.module.impl.exploit.AutoMineXMod;
import com.client.legitskillissue.module.impl.exploit.AutoParkourXMod;
import com.client.legitskillissue.module.impl.exploit.AutoPvPXMod;
import com.client.legitskillissue.module.impl.exploit.AutoReconnectXMod;
import com.client.legitskillissue.module.impl.exploit.AutoSneakXMod;
import com.client.legitskillissue.module.impl.exploit.AutoSprintXMod;
import com.client.legitskillissue.module.impl.exploit.AutoStealXMod;
import com.client.legitskillissue.module.impl.exploit.AutoSwordXMod;
import com.client.legitskillissue.module.impl.exploit.AutoTameXMod;
import com.client.legitskillissue.module.impl.exploit.AutoTotemXMod;
import com.client.legitskillissue.module.impl.exploit.AutoWalkXMod;
import com.client.legitskillissue.module.impl.exploit.AutoWeaponXMod;
import com.client.legitskillissue.module.impl.exploit.BaseFinderXMod;
import com.client.legitskillissue.module.impl.exploit.BedAuraXMod;
import com.client.legitskillissue.module.impl.exploit.BedESPXMod;
import com.client.legitskillissue.module.impl.exploit.BetterChatXMod;
import com.client.legitskillissue.module.impl.exploit.BlinkXMod;
import com.client.legitskillissue.module.impl.exploit.BlockESPXMod;
import com.client.legitskillissue.module.impl.exploit.BoatFlyXMod;
import com.client.legitskillissue.module.impl.exploit.BowAimbotXMod;
import com.client.legitskillissue.module.impl.exploit.BowSpamXMod;
import com.client.legitskillissue.module.impl.exploit.CameraNoClipXMod;
import com.client.legitskillissue.module.impl.exploit.CaveFinderXMod;
import com.client.legitskillissue.module.impl.exploit.ChatBypassXMod;
import com.client.legitskillissue.module.impl.exploit.ChestAuraXMod;
import com.client.legitskillissue.module.impl.exploit.ChestStealer2XMod;
import com.client.legitskillissue.module.impl.exploit.ClickAuraXMod;
import com.client.legitskillissue.module.impl.exploit.CompassESPXMod;
import com.client.legitskillissue.module.impl.exploit.CrashXMod;
import com.client.legitskillissue.module.impl.exploit.Criticals2XMod;
import com.client.legitskillissue.module.impl.exploit.DamageXMod;
import com.client.legitskillissue.module.impl.exploit.DayXMod;
import com.client.legitskillissue.module.impl.exploit.Derp2XMod;
import com.client.legitskillissue.module.impl.exploit.DolphinFlyXMod;
import com.client.legitskillissue.module.impl.exploit.ElytraFlyXMod;
import com.client.legitskillissue.module.impl.exploit.EntityDesyncXMod;
import com.client.legitskillissue.module.impl.exploit.EntitySpeedXMod;
import com.client.legitskillissue.module.impl.exploit.ExtraElytraXMod;
import com.client.legitskillissue.module.impl.exploit.FakeCreativeXMod;
import com.client.legitskillissue.module.impl.exploit.FakeGamemodeXMod;
import com.client.legitskillissue.module.impl.exploit.FakeHackerXMod;
import com.client.legitskillissue.module.impl.exploit.FakeLagXMod;
import com.client.legitskillissue.module.impl.exploit.FakePlayerXMod;
import com.client.legitskillissue.module.impl.exploit.FastBreakXMod;
import com.client.legitskillissue.module.impl.exploit.FastClimbXMod;
import com.client.legitskillissue.module.impl.exploit.FastFallXMod;
import com.client.legitskillissue.module.impl.exploit.FastLaddersXMod;
import com.client.legitskillissue.module.impl.exploit.FastUseXMod;
import com.client.legitskillissue.module.impl.exploit.Fly2XMod;
import com.client.legitskillissue.module.impl.exploit.ForceOPXMod;
import com.client.legitskillissue.module.impl.exploit.Freecam2XMod;
import com.client.legitskillissue.module.impl.exploit.Fullbright2XMod;
import com.client.legitskillissue.module.impl.exploit.GhostHandXMod;
import com.client.legitskillissue.module.impl.exploit.GlideXMod;
import com.client.legitskillissue.module.impl.exploit.GodModeXMod;
import com.client.legitskillissue.module.impl.exploit.HeadRollXMod;
import com.client.legitskillissue.module.impl.exploit.HighJumpXMod;
import com.client.legitskillissue.module.impl.exploit.Hitbox2XMod;
import com.client.legitskillissue.module.impl.exploit.HoverXMod;
import com.client.legitskillissue.module.impl.exploit.InfiniteReachXMod;
import com.client.legitskillissue.module.impl.exploit.InstaBreakXMod;
import com.client.legitskillissue.module.impl.exploit.InventoryMove2XMod;
import com.client.legitskillissue.module.impl.exploit.ItemESPXMod;
import com.client.legitskillissue.module.impl.exploit.Jesus2XMod;
import com.client.legitskillissue.module.impl.exploit.JetpackXMod;
import com.client.legitskillissue.module.impl.exploit.KillAura2XMod;
import com.client.legitskillissue.module.impl.exploit.LagSwitchXMod;
import com.client.legitskillissue.module.impl.exploit.LiquidInteractXMod;
import com.client.legitskillissue.module.impl.exploit.LongJumpXMod;
import com.client.legitskillissue.module.impl.exploit.MacroXMod;
import com.client.legitskillissue.module.impl.exploit.MagicCarpetXMod;
import com.client.legitskillissue.module.impl.exploit.MassTPAXMod;
import com.client.legitskillissue.module.impl.exploit.MobESPXMod;
import com.client.legitskillissue.module.impl.exploit.MultiAuraXMod;
import com.client.legitskillissue.module.impl.exploit.NameProtect2XMod;
import com.client.legitskillissue.module.impl.exploit.NightXMod;
import com.client.legitskillissue.module.impl.exploit.NoBackgroundXMod;
import com.client.legitskillissue.module.impl.exploit.NoClipXMod;
import com.client.legitskillissue.module.impl.exploit.NoFall2XMod;
import com.client.legitskillissue.module.impl.exploit.NoPitchLimitXMod;
import com.client.legitskillissue.module.impl.exploit.NoPushXMod;
import com.client.legitskillissue.module.impl.exploit.NoRenderXMod;
import com.client.legitskillissue.module.impl.exploit.NoSlow2XMod;
import com.client.legitskillissue.module.impl.exploit.NoSwingXMod;
import com.client.legitskillissue.module.impl.exploit.NoWeatherXMod;
import com.client.legitskillissue.module.impl.exploit.NukerXMod;
import com.client.legitskillissue.module.impl.exploit.OwoWalkXMod;
import com.client.legitskillissue.module.impl.exploit.PacketFlyXMod;
import com.client.legitskillissue.module.impl.exploit.PanicXMod;
import com.client.legitskillissue.module.impl.exploit.ParkourXMod;
import com.client.legitskillissue.module.impl.exploit.PhaseXMod;
import com.client.legitskillissue.module.impl.exploit.PlayerESP2XMod;
import com.client.legitskillissue.module.impl.exploit.PotionSaverXMod;
import com.client.legitskillissue.module.impl.exploit.Reach2XMod;
import com.client.legitskillissue.module.impl.exploit.RegenXMod;
import com.client.legitskillissue.module.impl.exploit.SafeWalk2XMod;
import com.client.legitskillissue.module.impl.exploit.Scaffold2XMod;
import com.client.legitskillissue.module.impl.exploit.SearchXMod;
import com.client.legitskillissue.module.impl.exploit.ServerCrasherXMod;
import com.client.legitskillissue.module.impl.exploit.Sneak2XMod;
import com.client.legitskillissue.module.impl.exploit.Speed2XMod;
import com.client.legitskillissue.module.impl.movement.AirJumpMod;
import com.client.legitskillissue.module.impl.movement.AntiVoidMod;
import com.client.legitskillissue.module.impl.movement.EagleMod;
import com.client.legitskillissue.module.impl.movement.FlightMod;
import com.client.legitskillissue.module.impl.movement.JesusMod;
import com.client.legitskillissue.module.impl.movement.KeepSprintMod;
import com.client.legitskillissue.module.impl.movement.NoFallMod;
import com.client.legitskillissue.module.impl.movement.NoSlowMod;
import com.client.legitskillissue.module.impl.movement.NoWebMod;
import com.client.legitskillissue.module.impl.movement.ParkourMod;
import com.client.legitskillissue.module.impl.movement.SpeedMod;
import com.client.legitskillissue.module.impl.movement.SpiderMod;
import com.client.legitskillissue.module.impl.movement.SprintMod;
import com.client.legitskillissue.module.impl.movement.StepMod;
import com.client.legitskillissue.module.impl.player.AutoArmorMod;
import com.client.legitskillissue.module.impl.player.AutoBlinkMod;
import com.client.legitskillissue.module.impl.player.AutoDisconnectMod;
import com.client.legitskillissue.module.impl.player.AutoRespawnMod;
import com.client.legitskillissue.module.impl.player.AutoToolMod;
import com.client.legitskillissue.module.impl.player.ChestStealerMod;
import com.client.legitskillissue.module.impl.player.CreativeModeMod;
import com.client.legitskillissue.module.impl.player.DerpMod;
import com.client.legitskillissue.module.impl.player.DisablerMod;
import com.client.legitskillissue.module.impl.player.FastDropMod;
import com.client.legitskillissue.module.impl.player.FastEatMod;
import com.client.legitskillissue.module.impl.player.FastPlaceMod;
import com.client.legitskillissue.module.impl.player.InvMoveMod;
import com.client.legitskillissue.module.impl.player.InventoryManagerMod;
import com.client.legitskillissue.module.impl.player.ScaffoldMod;
import com.client.legitskillissue.module.impl.player.SneakMod;
import com.client.legitskillissue.module.impl.player.TimerMod;
import com.client.legitskillissue.module.impl.render.BreadcrumbsMod;
import com.client.legitskillissue.module.impl.render.ChamsMod;
import com.client.legitskillissue.module.impl.render.ChestESPMod;
import com.client.legitskillissue.module.impl.render.FreecamMod;
import com.client.legitskillissue.module.impl.render.FullbrightMod;
import com.client.legitskillissue.module.impl.render.NameProtectMod;
import com.client.legitskillissue.module.impl.render.NametagsMod;
import com.client.legitskillissue.module.impl.render.NoHurtCamMod;
import com.client.legitskillissue.module.impl.render.PlayerESPMod;
import com.client.legitskillissue.module.impl.render.TargetHUDMod;
import com.client.legitskillissue.module.impl.render.TracersMod;
import com.client.legitskillissue.module.impl.render.XRayMod;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import net.minecraft.network.Packet;

public class ModuleManager {
    public static final ModuleManager INSTANCE = new ModuleManager();
    private final List<Module> modules = new ArrayList<>();

    private ModuleManager() {
        modules.add(new AimAssistMod());
        modules.add(new AirJumpMod());
        modules.add(new AntiAimXMod());
        modules.add(new AntiBlindXMod());
        modules.add(new AntiBotMod());
        modules.add(new AntiCactusXMod());
        modules.add(new AntiFireXMod());
        modules.add(new AntiKnockbackXMod());
        modules.add(new AntiPotionXMod());
        modules.add(new AntiSpamXMod());
        modules.add(new AntiVoidMod());
        modules.add(new AntiWaterXMod());
        modules.add(new AutoAcceptXMod());
        modules.add(new AutoArmor2XMod());
        modules.add(new AutoArmorMod());
        modules.add(new AutoBlinkMod());
        modules.add(new AutoBuildXMod());
        modules.add(new AutoClickerMod());
        modules.add(new AutoClickerXMod());
        modules.add(new AutoDisconnectMod());
        modules.add(new AutoDropXMod());
        modules.add(new AutoEatXMod());
        modules.add(new AutoFarmXMod());
        modules.add(new AutoFishXMod());
        modules.add(new AutoHealXMod());
        modules.add(new AutoJumpXMod());
        modules.add(new AutoLeaveXMod());
        modules.add(new AutoMineXMod());
        modules.add(new AutoParkourXMod());
        modules.add(new AutoPotMod());
        modules.add(new AutoPvPXMod());
        modules.add(new AutoReconnectXMod());
        modules.add(new AutoRespawnMod());
        modules.add(new AutoSneakXMod());
        modules.add(new AutoSoupMod());
        modules.add(new AutoSprintXMod());
        modules.add(new AutoStealXMod());
        modules.add(new AutoSwordXMod());
        modules.add(new AutoTameXMod());
        modules.add(new AutoToolMod());
        modules.add(new AutoTotemXMod());
        modules.add(new AutoWalkXMod());
        modules.add(new AutoWeaponXMod());
        modules.add(new BacktrackMod());
        modules.add(new BaseFinderXMod());
        modules.add(new BedAuraXMod());
        modules.add(new BedESPXMod());
        modules.add(new BetterChatXMod());
        modules.add(new BlinkXMod());
        modules.add(new BlockESPXMod());
        modules.add(new BlockHitMod());
        modules.add(new BoatFlyXMod());
        modules.add(new BowAimbotXMod());
        modules.add(new BowSpamXMod());
        modules.add(new BreadcrumbsMod());
        modules.add(new CameraNoClipXMod());
        modules.add(new CaveFinderXMod());
        modules.add(new ChamsMod());
        modules.add(new ChatBypassXMod());
        modules.add(new ChestAuraXMod());
        modules.add(new ChestESPMod());
        modules.add(new ChestStealer2XMod());
        modules.add(new ChestStealerMod());
        modules.add(new ClickAuraXMod());
        modules.add(new CompassESPXMod());
        modules.add(new CrashXMod());
        modules.add(new CreativeModeMod());
        modules.add(new Criticals2XMod());
        modules.add(new CriticalsMod());
        modules.add(new DamageXMod());
        modules.add(new DayXMod());
        modules.add(new Derp2XMod());
        modules.add(new DerpMod());
        modules.add(new DisablerMod());
        modules.add(new DolphinFlyXMod());
        modules.add(new EagleMod());
        modules.add(new ElytraFlyXMod());
        modules.add(new EntityDesyncXMod());
        modules.add(new EntitySpeedXMod());
        modules.add(new ExtraElytraXMod());
        modules.add(new FakeCreativeXMod());
        modules.add(new FakeGamemodeXMod());
        modules.add(new FakeHackerXMod());
        modules.add(new FakeLagXMod());
        modules.add(new FakePlayerXMod());
        modules.add(new FastBowMod());
        modules.add(new FastBreakXMod());
        modules.add(new FastClimbXMod());
        modules.add(new FastDropMod());
        modules.add(new FastEatMod());
        modules.add(new FastFallXMod());
        modules.add(new FastLaddersXMod());
        modules.add(new FastPlaceMod());
        modules.add(new FastUseXMod());
        modules.add(new FlightMod());
        modules.add(new Fly2XMod());
        modules.add(new ForceOPXMod());
        modules.add(new Freecam2XMod());
        modules.add(new FreecamMod());
        modules.add(new Fullbright2XMod());
        modules.add(new FullbrightMod());
        modules.add(new GhostHandXMod());
        modules.add(new GlideXMod());
        modules.add(new GodModeXMod());
        modules.add(new HeadRollXMod());
        modules.add(new HighJumpXMod());
        modules.add(new HitBoxMod());
        modules.add(new HitDelayFixMod());
        modules.add(new Hitbox2XMod());
        modules.add(new HoverXMod());
        modules.add(new InfiniteReachXMod());
        modules.add(new InstaBreakXMod());
        modules.add(new InvMoveMod());
        modules.add(new InventoryManagerMod());
        modules.add(new InventoryMove2XMod());
        modules.add(new ItemESPXMod());
        modules.add(new Jesus2XMod());
        modules.add(new JesusMod());
        modules.add(new JetpackXMod());
        modules.add(new KeepSprintMod());
        modules.add(new KillAura2XMod());
        modules.add(new LagSwitchXMod());
        modules.add(new LiquidInteractXMod());
        modules.add(new LongJumpXMod());
        modules.add(new MacroXMod());
        modules.add(new MagicCarpetXMod());
        modules.add(new MassTPAXMod());
        modules.add(new MobESPXMod());
        modules.add(new MultiAuraXMod());
        modules.add(new NameProtect2XMod());
        modules.add(new NameProtectMod());
        modules.add(new NametagsMod());
        modules.add(new NightXMod());
        modules.add(new NoBackgroundXMod());
        modules.add(new NoClipXMod());
        modules.add(new NoFall2XMod());
        modules.add(new NoFallMod());
        modules.add(new NoHurtCamMod());
        modules.add(new NoPitchLimitXMod());
        modules.add(new NoPushXMod());
        modules.add(new NoRenderXMod());
        modules.add(new NoSlow2XMod());
        modules.add(new NoSlowMod());
        modules.add(new NoSwingXMod());
        modules.add(new NoWeatherXMod());
        modules.add(new NoWebMod());
        modules.add(new NukerXMod());
        modules.add(new OwoWalkXMod());
        modules.add(new PacketFlyXMod());
        modules.add(new PanicXMod());
        modules.add(new ParkourMod());
        modules.add(new ParkourXMod());
        modules.add(new PhaseXMod());
        modules.add(new PlayerESP2XMod());
        modules.add(new PlayerESPMod());
        modules.add(new PotionSaverXMod());
        modules.add(new Reach2XMod());
        modules.add(new ReachMod());
        modules.add(new RegenXMod());
        modules.add(new SafeWalk2XMod());
        modules.add(new Scaffold2XMod());
        modules.add(new ScaffoldMod());
        modules.add(new SearchXMod());
        modules.add(new ServerCrasherXMod());
        modules.add(new SilentAuraMod());
        modules.add(new Sneak2XMod());
        modules.add(new SneakMod());
        modules.add(new Speed2XMod());
        modules.add(new SpeedMod());
        modules.add(new SpiderMod());
        modules.add(new SprintMod());
        modules.add(new StepMod());
        modules.add(new TargetHUDMod());
        modules.add(new TargetSelectorMod());
        modules.add(new TimerMod());
        modules.add(new TracersMod());
        modules.add(new TriggerBotMod());
        modules.add(new VelocityMod());
        modules.add(new WTapMod());
        modules.add(new XRayMod());
    }

    public List<Module> getModules() {
        return Collections.unmodifiableList(modules);
    }

    public <T extends Module> T getModule(Class<T> clazz) {
        for (Module m : modules) {
            if (m.getClass() == clazz) return (T) m;
        }
        return null;
    }

    public void onKey(int key) {
        for (Module m : modules) {
            if (m.getKeybind() == key) m.toggle();
        }
    }

    public void onMouseClick(net.minecraftforge.client.event.MouseEvent event) {
        for (Module m : modules) {
            if (m.isEnabled()) m.onMouseClick(event);
        }
    }

    public boolean onPacketSend(Packet<?> packet) {
        for (Module m : modules) {
            if (m.isEnabled() && m.onPacketSend(packet)) return true;
        }
        return false;
    }

    public boolean onPacketReceive(Packet<?> packet) {
        for (Module m : modules) {
            if (m.isEnabled() && m.onPacketReceive(packet)) return true;
        }
        return false;
    }
}
